apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: cluster-plural-cloud-demo-workload-00
spec:
  name: cluster-plural-cloud-demo-workload-00
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  configuration:
    version: '1.8'
  repositoryRef:
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
  variables:
    cluster: plural-cloud-demo-workload-00
    fleet: plural-cloud-demo
    tier: dev
  git:
    ref: main
    folder: terraform/modules/clusters/aws
